name: Build

on:
  push:
    branches: main
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jupyterlab: ['2.0', '3.0']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
          architecture: 'x64'

      - name: Install dependencies
        run: python -m pip install jupyterlab~=${{ matrix.jupyterlab }}

      - name: Build the extension
        run: |
          jlpm
          jlpm run eslint:check

          pip install .
          jupyter lab build
          jupyter serverextension list 1>serverextensions 2>&1
          cat serverextensions | grep "jupyterlab_hdf.*OK"
          jupyter labextension list 1>labextensions 2>&1
          cat labextensions | grep "jupyterlab-h5web.*OK"

          python -m jupyterlab.browser_check
