name: Build for JupyterLab 2

on:
  push:
    branches:
      - 0.x
  pull_request:
    branches:
      - 0.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🏷️
        uses: actions/checkout@v2

      - name: Use Node 14 🕹️
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install Python 🐍
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
          architecture: 'x64'

      - name: Install dependencies ⚙️
        run: python -m pip install -U jupyterlab~=2.0

      - name: Build the extension 🏗️
        run: |
          set -eux
          jlpm
          jlpm run lint
          python -m pip install .
          jupyter labextension install .
          jupyter lab build

          jupyter serverextension list 2>&1 | grep -ie "jupyterlab_h5web.*OK"
          jupyter labextension list 2>&1 | grep -ie "jupyterlab-h5web.*OK"

          python -m jupyterlab.browser_check

      - name: Upload debug logs on failure 📬
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Build log
          path: |
            /tmp/*.log
