name: Release 0.x

on:
  push:
    tags:
      - v0.*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🏷️
        uses: actions/checkout@v2

      - name: Match tag to package version 🧐
        uses: geritol/match-tag-to-package-version@0.0.2
        env:
          TAG_PREFIX: refs/tags/v

      - name: Use Node 14 🕹️
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Python 🐍
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
          architecture: 'x64'

      - name: Install dependencies ⚙️
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_release.txt

      - name: Build the package 🔧
        run: python setup.py sdist bdist_wheel

      - name: Publish package on PyPI 🎉
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
