name: Release

on:
  push:
    tags:
      - 'v*'
      - '!v0.*'

jobs:
  build:
    uses: silx-kit/jupyterlab-h5web/.github/workflows/build.yml@8.x
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download the built extension
        uses: actions/download-artifact@v2
        with:
          name: jupyterlab_h5web-dist
          path: dist

      - name: Publish package on PyPI 🎉
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
